name: mamba-tests
channels:
  - conda-forge
  - defaults
dependencies:
  - vs2017_win-64
  - python=3.7
  - pip
  - pybind11
  - libsolv
  - libarchive
  - libcurl
  - nlohmann_json
  - cpp-filesystem
  - conda
  - cmake
  - gtest
  - ninja
  - reproc-cpp
  - yaml-cpp
  - cli11
  - pygithub
  - git
  - vcpkg
