name: mamba-dev
channels:
  - conda-forge
dependencies:
  - cmake
  - make
  - ninja
  - nlohmann_json
  - pybind11
  - libsolv >=0.7.18
  - libarchive
  - libsodium
  - libcurl 7.76.1 *_0
  - cxx-compiler
  - gtest
  - gmock
  - cpp-filesystem
  - reproc-cpp
  - yaml-cpp
  - pyyaml
  - cli11
  - pytest
    #  - krb5-static
    #  - libcurl-static 7.76.1 *_0
    #  - libnghttp2-static
    #  - libopenssl-static
    #  - libxml2
    #  - libsolv-static >=0.7.18
    #  - libssh2-static
    #  - lz4-c-static
    #  - reproc-cpp-static
    #  - reproc-static
    #  - yaml-cpp-static
    #  - xz-static
    #  - zstd-static
