name: mamba-tests
channels:
  - conda-forge
  - defaults
dependencies:
  - pybind11
  - libsolv
  - libarchive
  - libcurl
  - nlohmann_json
  - cxx-compiler
  - cmake
  - gtest
  - cpp-filesystem
  - reproc-cpp
  - yaml-cpp
  - cli11
  - pygithub
