name: mamba-tests
channels:
  - conda-forge
  - defaults
dependencies:
  - curl
  - pybind11
  - libsolv
  - libarchive
  - libcurl
  - nlohmann_json
  - cxx-compiler
  - cmake
  - gtest
  - cpp-filesystem
  - reproc-cpp
  - yaml-cpp
  - cli11
  - pygithub
  - yaml-cpp-static
  - libcurl-static
  - xz-static
  - libssh2-static
  - krb5-static
  - libsolv-static
  - libopenssl-static
  - zstd-static
  - libnghttp2-static
  - lz4-c-static
  - reproc-static
  - reproc-cpp-static
  - libxml2
