name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2016]
        python-version: [ '3.6', '3.7', '3.8']

    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Create the conda environment
        shell: bash -l {0}
        run: |
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda install -q -y python=$PYTHON_VERSION pip pybind11 libsolv libarchive libcurl nlohmann_json cxx-compiler conda
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          python --version
          python -m pip install ".[test]"
      - name: Run tests
        shell: bash -l {0}
        run: |
          source "$CONDA/etc/profile.d/conda.sh"
          py.test test
          mamba create -n test_env xtensor -c conda-forge --mamba-download -y
